# cert-manager - automatically provisions SSL certificates from Let's Encrypt
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.2
    helm:
      releaseName: cert-manager
      valueFiles:
        - https://raw.githubusercontent.com/Rania193/DevOps-CES-Challenge/main/helm/values/cert-manager.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

